import { CueWorkoutCard } from '../../../../Model';

export const CUE_CARDS: { [key: string]: CueWorkoutCard } = {
  red: {
    id: 'red',
    label: '赤',
    pitchStr: 'あ＼か',
    imagePath: '/images/red.png',
    hasTailAccent: false,
  },
  blue: {
    id: 'blue',
    label: '青',
    pitchStr: 'あ＼お',
    imagePath: '/images/blue.png',
    hasTailAccent: false,
  },
  green: {
    id: 'green',
    label: '緑',
    pitchStr: 'み＼どり',
    imagePath: '/images/green.png',
    hasTailAccent: false,
  },
  hikkurikaesu: {
    id: 'hikkurikaesu',
    label: 'ひっくりかえす',
    pitchStr: 'ひっくりか＼えす',
    imagePath: '/images/hikkurikaesu.png',
    hasTailAccent: false,
  },
  ireru: {
    id: 'ireru',
    label: '入れる',
    pitchStr: 'いれる',
    imagePath: '/images/ireru.png',
    hasTailAccent: false,
  },
  kabuseru: {
    id: 'kabuseru',
    label: '被せる',
    pitchStr: 'かぶせ＼る',
    imagePath: '/images/kabuseru.png',
    hasTailAccent: false,
  },
  motsu: {
    id: 'motsu',
    label: '持つ',
    pitchStr: 'も＼つ',
    imagePath: '/images/motsu.png',
    hasTailAccent: false,
  },
  noseru: {
    id: 'noseru',
    label: 'のせる',
    pitchStr: 'のせる',
    imagePath: '/images/noseru.png',
    hasTailAccent: false,
  },
  orange: {
    id: 'orange',
    label: 'オレンジ',
    pitchStr: 'オレ＼ンジ',
    imagePath: '/images/orange.png',
    hasTailAccent: false,
  },
  pink: {
    id: 'pink',
    label: 'ピンク',
    pitchStr: 'ピ＼ンク',
    imagePath: '/images/pink.png',
    hasTailAccent: false,
  },
  yellow: {
    id: 'yellow',
    label: '黄色',
    pitchStr: 'きいろ',
    imagePath: '/images/yellow.png',
    hasTailAccent: false,
  },
  yubisasu: {
    id: 'yubisasu',
    label: 'ゆびさす',
    pitchStr: 'ゆびさ＼す',
    imagePath: '/images/yubisasu.png',
    hasTailAccent: false,
  },
  mine: {
    id: 'mine',
    label: 'わたしのて',
    pitchStr: 'わたしのて',
    imagePath: '',
    hasTailAccent: true,
  },
  yours: {
    id: 'yours',
    label: 'じぶんのて',
    pitchStr: 'じぶんのて',
    imagePath: '',
    hasTailAccent: true,
  },
  right: {
    id: 'right',
    label: '一番右の',
    pitchStr: 'いちばん　みぎの',
    imagePath: '',
    hasTailAccent: true,
  },
  left: {
    id: 'left',
    label: '一番左の',
    pitchStr: 'いちばん　ひだりの',
    imagePath: '',
    hasTailAccent: true,
  },
};
